# Generated by Django 5.2.5 on 2025-08-11 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContextEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("note", "Note"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_metadata", models.JSONField(blank=True, default=dict)),
                ("processed_insights", models.JSONField(blank=True, default=dict)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
