# Generated by Django 5.2.5 on 2025-08-11 04:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("contexts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("archived", "Archived"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("priority_score", models.FloatField(default=0.0)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("ai_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.category",
                    ),
                ),
                (
                    "contexts",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="contexts.contextentry"
                    ),
                ),
            ],
            options={
                "ordering": ["-priority_score", "due_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["priority_score"], name="tasks_task_priorit_2bdd1c_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="tasks_task_due_dat_bce847_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tasks_task_created_be1ba2_idx"
                    ),
                ],
            },
        ),
    ]
