# Generated by Django 5.2.5 on 2025-08-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_owner"),
        ("tasks", "0002_task_owner"),
    ]

    operations = []
